Enabled: true
StartTime: '2015-11-22-22:00:00'
EndTime: '2015-11-22-23:59:00'
TitlePrefix: '&3&lEvent '
TitleSuffix: ''
Messages:
- ''
- '&fWarp: &3/build'
- '&fTeamSpeak:'
- '&3winthier.enjinvoice.com'
