main: com.winthier.countdown.CountdownPlugin
name: Countdown

version: 0.1
api-version: 1.17

author: StarTux
description: Display a countdown in the Sidebar
website: https://github.com/StarTux/Countdown

depend: [Sidebar]
softdepend: []

commands:

  countdown:
    description: Admin interface
    permission: countdown.countdown
    usage: /<command> reload

permissions:

  countdown.countdown:
    description: Use /countdown
    default: op
