name: Countdown
description: Display a countdown in the sidebar
version: 0.1
author: StarTux
main: com.winthier.countdown.CountdownPlugin
website: https://github.com/StarTux/Countdown
api-version: 1.13
depend: []
softdepend: []
commands:
  countdown:
    description: Admin interface
    permission: countdown.countdown
    usage: /<command> reload
  sidebar:
    description: User interface
    permission: countdown.sidebar
    usage: /<command> on|off
permissions:
  countdown.countdown:
    description: Use /countdown
    default: op
